language: php

sudo: false

branches:
  only: [ master ]

php:
  - 5.6
  - hhvm
  - 7.0
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_install:
  - travis_retry composer selfupdate

install:
  - travis_retry composer.phar update --prefer-source

script:
  - ./test.sh
